# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=10)),
            ],
        ),
    ]
